spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./build/libraries
    username: sa
    password:

  thymeleaf.check-template-location: false
  groovy.template.enabled: false
